#!/bin/bash
Server_Not_Found(){
	echo -e "\n${Error}输入错误或${Server_Name}服务器不存在！"
	if [[ $UseMenu -eq "1" ]];then
		read -e "回车返回"
		clear
		Server_List
	else
		exit 0
	fi
}

Server_Check(){
	if [ -z "`list&&echo "$alist"|grep -w $Server_Name`" ];then #查找服务器是否存在
		Server_Not_Found
	else
		$Server_Name
	fi
}

Server_List(){
	if [[ $action == "web" ]];then
		clear&&Web_contorl
	elif [[ $UseMenu -eq "1" ]];then #判断是否是从菜单进来的
		logo
		echo -e "${Info}服务器选择${Font_suffix} ${Powered}"
		list&&echo "$list"|awk '{print FNR". "$0}' #打印数字，方便选择
		echo -e "q. 返回主菜单\n"
		read -p "请选择:" ServerChoice
		if [ "$ServerChoice" == "0" ]||[[ "$ServerChoice" == "q" ]];then
			MainMenu
		elif [[ "$ServerChoice" =~ ^[0-9]+$ ]];then
			Server_Name=`list&&echo "$list"|sed -n "${ServerChoice}p"|sed 's/ //g'`
			Server_Check
		else
			Server_Not_Found
		fi
	else
		Server_Check
	fi
	if [[ $UseMenu -eq "0" ]];then
		Server_Action
	elif [[ $Group == "true" ]];then
		Group_List
	else
		Server_Action
	fi
}